# Generated by Django 4.2.6 on 2023-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('car_brand', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
